import"./assets/styles-C1jZxY8C.js";import{a as r}from"./assets/vendor-C19taMLP.js";const c={categories:document.querySelector(".categories"),products:document.querySelector(".products"),notFound:document.querySelector(".not-found"),loadMoreButton:document.querySelector(".moreButton"),modal:document.querySelector(".modal"),modalProduct:document.querySelector(".modal-product"),closeModalBtn:document.querySelector(".modal__close-btn"),searchForm:document.querySelector(".search-form"),searchInput:document.querySelector(".search-form__input"),searchClear:document.querySelector(".search-form__btn-clear"),btnAddCartModal:document.querySelector(".modal-product__btn--cart"),btnAddWishlistModal:document.querySelector(".modal-product__btn--wishlist"),navCountCart:document.querySelector("[data-cart-count]"),navCountWishlist:document.querySelector("[data-wishlist-count]"),itemsCart:document.querySelector("[data-count]"),totalCart:document.querySelector("[data-price]"),buyProductsBtn:document.querySelector(".cart-summary__btn"),scrollUpBtn:document.getElementById("scrollUpBtn"),toggleTheme:document.querySelector('[type="checkbox"]')};r.defaults.baseURL="https://dummyjson.com/products";async function f(){try{return(await r.get("/category-list")).data}catch(t){return console.log(t),null}}async function b(t=1){const e={limit:12,skip:(t-1)*12};return(await r.get("",{params:e})).data}async function L(t,e=1){const o={limit:12,skip:(e-1)*12};let n=`/category/${t}`;return t==="ALL"&&(n=""),(await r.get(n,{params:o})).data}async function h(t){return(await r.get(`/${t}`)).data}function v(t){t.unshift("ALL");const e=t.map(o=>`<li class="categories__item">
   <button class="categories__btn" type="button">${o}</button>
 </li>
`).join("");c.categories.innerHTML=e}function p(t){const e=t.map(({id:o,title:n,description:s,brand:d,thumbnail:i,category:l,price:u})=>`<li class="products__item" data-id="${o}">
    <img class="products__image" src="${i}" alt="${s}"/>
    <p class="products__title">${n}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:${d}</span></p>
    <p class="products__category">Category:${l} </p>
    <p class="products__price">Price:${u} $</p>
 </li>`).join("");c.products.insertAdjacentHTML("beforeend",e)}function $(t){const{title:e,description:o,price:n,thumbnail:s,returnPolicy:d,shippingInformation:i,tags:l}=t,u=l.map(y=>`<li class="modal-product__tag">${y}</li>`).join(""),g=`<img class="modal-product__img" src="${s}" alt="${o}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${e}</p>
        <ul class="modal-product__tags">${u}</ul>
        <p class="modal-product__description">${o}</p>
        <p class="modal-product__shipping-information">Shipping:${i}</p>
        <p class="modal-product__return-policy">Return Policy:${d}</p>
        <p class="modal-product__price">Price:${n} $</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div>
`;c.modalProduct.innerHTML=g}function S(){c.modal.classList.add("modal--is-open"),document.addEventListener("keydown",m),window.addEventListener("click",_),c.closeModalBtn.addEventListener("click",a)}function a(){c.modal.classList.remove("modal--is-open"),document.removeEventListener("keydown",m),window.removeEventListener("click",_),c.closeModalBtn.removeEventListener("click",a)}function m(t){t.key==="Escape"&&a()}function _(t){t.target===c.modal&&a()}async function k(t){if(!t.target.classList.contains("categories__btn"))return;const e=t.target.textContent,o=await L(e);c.products.innerHTML="",console.log(o),o.total===0?c.notFound.classList.add("not-found--visible"):(c.notFound.classList.remove("not-found--visible"),p(o.products)),c.categories.querySelectorAll(".categories__btn").forEach(n=>{n.classList.remove("categories__btn--active")}),t.target.classList.add("categories__btn--active")}async function q(t){const e=t.target.closest(".products__item");if(!e)return;const o=e.dataset.id;S();const n=await h(o);console.log(n),$(n)}async function M(){const t=await f(),e=await b();t?v(t):c.categories.innerHTML="not found",p(e.products)}M();c.categories.addEventListener("click",k);c.products.addEventListener("click",q);
//# sourceMappingURL=index.js.map
