import"./assets/styles-C1jZxY8C.js";import{a as r}from"./assets/vendor-C19taMLP.js";const o={categories:document.querySelector(".categories"),products:document.querySelector(".products"),notFound:document.querySelector(".not-found"),loadMoreButton:document.querySelector(".moreButton"),modal:document.querySelector(".modal"),modalProduct:document.querySelector(".modal-product"),closeModalBtn:document.querySelector(".modal__close-btn"),searchForm:document.querySelector(".search-form"),searchInput:document.querySelector(".search-form__input"),searchClear:document.querySelector(".search-form__btn-clear"),btnAddCartModal:document.querySelector(".modal-product__btn--cart"),btnAddWishlistModal:document.querySelector(".modal-product__btn--wishlist"),navCountCart:document.querySelector("[data-cart-count]"),navCountWishlist:document.querySelector("[data-wishlist-count]"),itemsCart:document.querySelector("[data-count]"),totalCart:document.querySelector("[data-price]"),buyProductsBtn:document.querySelector(".cart-summary__btn"),scrollUpBtn:document.getElementById("scrollUpBtn"),toggleTheme:document.querySelector('[type="checkbox"]')};r.defaults.baseURL="https://dummyjson.com/products";async function f(){try{return(await r.get("/category-list")).data}catch(t){return console.log(t),null}}async function b(t=1){const e={limit:12,skip:(t-1)*12};return(await r.get("",{params:e})).data}async function h(t,e=1){const c={limit:12,skip:(e-1)*12};let n=`/category/${t}`;return t==="ALL"&&(n=""),(await r.get(n,{params:c})).data}async function L(t){return(await r.get(`/${t}`)).data}async function v(t,e=1){const c={limit:12,skip:(e-1)*12,q:t};return(await r.get("/search",{params:c})).data}function P(t){t.unshift("ALL");const e=t.map(c=>`<li class="categories__item">
   <button class="categories__btn" type="button">${c}</button>
 </li>
`).join("");o.categories.innerHTML=e}function p(t){const e=t.map(({id:c,title:n,description:s,brand:d,thumbnail:i,category:u,price:l})=>`<li class="products__item" data-id="${c}">
    <img class="products__image" src="${i}" alt="${s}"/>
    <p class="products__title">${n}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:${d}</span></p>
    <p class="products__category">Category:${u} </p>
    <p class="products__price">Price:${l} $</p>
 </li>`).join("");o.products.insertAdjacentHTML("beforeend",e)}function $(t){const{title:e,description:c,price:n,thumbnail:s,returnPolicy:d,shippingInformation:i,tags:u}=t,l=u.map(g=>`<li class="modal-product__tag">${g}</li>`).join(""),y=`<img class="modal-product__img" src="${s}" alt="${c}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${e}</p>
        <ul class="modal-product__tags">${l}</ul>
        <p class="modal-product__description">${c}</p>
        <p class="modal-product__shipping-information">Shipping:${i}</p>
        <p class="modal-product__return-policy">Return Policy:${d}</p>
        <p class="modal-product__price">Price:${n} $</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div>
`;o.modalProduct.innerHTML=y}function k(){o.modal.classList.add("modal--is-open"),document.addEventListener("keydown",m),window.addEventListener("click",_),o.closeModalBtn.addEventListener("click",a)}function a(){o.modal.classList.remove("modal--is-open"),document.removeEventListener("keydown",m),window.removeEventListener("click",_),o.closeModalBtn.removeEventListener("click",a)}function m(t){t.key==="Escape"&&a()}function _(t){t.target===o.modal&&a()}async function q(t){if(!t.target.classList.contains("categories__btn"))return;const e=t.target.textContent,c=await h(e);o.products.innerHTML="",console.log(c),c.total===0?o.notFound.classList.add("not-found--visible"):(o.notFound.classList.remove("not-found--visible"),p(c.products)),o.categories.querySelectorAll(".categories__btn").forEach(n=>{n.classList.remove("categories__btn--active")}),t.target.classList.add("categories__btn--active")}async function S(t){const e=t.target.closest(".products__item");if(!e)return;const c=e.dataset.id;k();const n=await L(c);console.log(n),$(n)}async function M(t){t.preventDefault();const e=o.searchInput.value.trim();if(e==="")return;const c=await v(e);o.products.innerHTML="",c.total===0?o.notFound.classList.add("not-found--visible"):(o.notFound.classList.remove("not-found--visible"),p(c.products)),o.searchForm.reset()}async function w(){const t=await f(),e=await b();t?P(t):o.categories.innerHTML="not found",p(e.products)}w();o.categories.addEventListener("click",q);o.products.addEventListener("click",S);o.searchForm.addEventListener("submit",M);
//# sourceMappingURL=index.js.map
