import"./assets/styles-C1jZxY8C.js";import{a}from"./assets/vendor-C19taMLP.js";const c={categories:document.querySelector(".categories"),products:document.querySelector(".products"),loadMoreButton:document.querySelector(".moreButton"),modal:document.querySelector(".modal"),modalProduct:document.querySelector(".modal-product"),closeModalBtn:document.querySelector(".modal__close-btn"),searchForm:document.querySelector(".search-form"),searchInput:document.querySelector(".search-form__input"),searchClear:document.querySelector(".search-form__btn-clear"),btnAddCartModal:document.querySelector(".modal-product__btn--cart"),btnAddWishlistModal:document.querySelector(".modal-product__btn--wishlist"),navCountCart:document.querySelector("[data-cart-count]"),navCountWishlist:document.querySelector("[data-wishlist-count]"),itemsCart:document.querySelector("[data-count]"),totalCart:document.querySelector("[data-price]"),buyProductsBtn:document.querySelector(".cart-summary__btn"),scrollUpBtn:document.getElementById("scrollUpBtn"),toggleTheme:document.querySelector('[type="checkbox"]')};a.defaults.baseURL="https://dummyjson.com/products";async function m(){try{const e=await a.get("/category-list");return console.log(e.data),e.data}catch(t){return console.log(t),null}}async function p(t=1){const e={limit:12,skip:(t-1)*12};return(await a.get("",{params:e})).data}async function g(t,e=1){const o={limit:12,skip:(e-1)*12},r=`/category/${t}`;return(await a.get(r,{params:o})).data}function y(t){t.unshift("ALL");const e=t.map(o=>`<li class="categories__item">
   <button class="categories__btn" type="button">${o}</button>
 </li>
`).join("");c.categories.innerHTML=e}function n(t){const e=t.map(({id:o,title:r,description:s,brand:u,thumbnail:d,category:i,price:l})=>`<li class="products__item" data-id="${o}">
    <img class="products__image" src="${d}" alt="${s}"/>
    <p class="products__title">${r}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:${u}</span></p>
    <p class="products__category">Category:${i} </p>
    <p class="products__price">Price:${l} $</p>
 </li>`).join("");c.products.insertAdjacentHTML("beforeend",e)}async function _(t){if(!t.target.classList.contains("categories__btn"))return;const e=t.target.textContent;console.log(e);const o=await g(e);c.products.innerHTML="",n(o.products),c.categories.querySelectorAll(".categories__btn").forEach(r=>{r.classList.remove("categories__btn--active")}),t.target.classList.add("categories__btn--active")}async function b(){const t=await m(),e=await p();console.log(t),t?y(t):c.categories.innerHTML="not found",n(e.products)}b();c.categories.addEventListener("click",_);
//# sourceMappingURL=index.js.map
